/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ADropdownButton: typeof import('ant-design-vue/es')['DropdownButton']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AResult: typeof import('ant-design-vue/es')['Result']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    BlockButton: typeof import('./src/components/users/table/buttons/BlockButton.vue')['default']
    ButtonsSpace: typeof import('./src/components/users/table/buttons/ButtonsSpace.vue')['default']
    DateColumn: typeof import('./src/components/users/table/columns/DateColumn.vue')['default']
    DeleteOption: typeof import('./src/components/users/table/buttons/DeleteOption.vue')['default']
    EmailColumn: typeof import('./src/components/users/table/columns/EmailColumn.vue')['default']
    FilterButton: typeof import('./src/components/users/table/buttons/FilterButton.vue')['default']
    IsBlockedColumn: typeof import('./src/components/users/table/columns/IsBlockedColumn.vue')['default']
    OptionsButton: typeof import('./src/components/users/table/buttons/OptionsButton.vue')['default']
    PhoneNumberColumn: typeof import('./src/components/users/table/columns/PhoneNumberColumn.vue')['default']
    RolesColumn: typeof import('./src/components/users/table/columns/RolesColumn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/users/table/SearchInput.vue')['default']
    TabList: typeof import('./src/components/todo/TabList.vue')['default']
    TaskForm: typeof import('./src/components/todo/TaskForm.vue')['default']
    TaskList: typeof import('./src/components/todo/TaskList.vue')['default']
    TheHeader: typeof import('./src/components/users/table/TheHeader.vue')['default']
    TheModal: typeof import('./src/components/users/table/TheModal.vue')['default']
    TheProfile: typeof import('./src/components/TheProfile.vue')['default']
    TheTask: typeof import('./src/components/todo/TheTask.vue')['default']
    ViewProfileButton: typeof import('./src/components/users/table/buttons/ViewProfileButton.vue')['default']
  }
}
